## Common
spring:
  application:
    name: products
  profiles:
    active:
      - local
---
## Local
spring:
  config:
    activate:
      on-profile:
      - local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    username: sa
    password: 
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080